config/routes.rb
Rails.application.routes.draw do

  root 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  

  resources :users do
    resources :posts
    resources :ratings
  end

resources :conversations do
  resources :messages
 end


  get '/home' => 'users#index'


end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password


  has_many :posts
  has_many :ratings
  has_many :conversations


  has_attached_file :avatar, styles: { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":assets/:medium/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates_presence_of :username, :email, :password_digest, :role, :service
  validates_uniqueness_of :username, :email


  def average_rating(array)
    sum = 0
    array.each do |rating|
      sum += rating
    end
    return (sum / array.length)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.all
    @posts = Post.all
  end



  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @conversations = Conversation.all
    @ratings = Rating.all
  end

  def new
    @user = User.new
    @rating = Rating.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.registration_confirmation(@user).deliver
      session[:user_id] = @user.id
      flash[:notice] = "Account successfully created"
      redirect_to users_path
    else
      render :new
    end
    @rating = Rating.new
  end



  def edit
    @user = User.find(params[:id])
  end



  def update
    @user = User.find(params[:id])
    @user.update_attribute(:avatar, params[:user][:avatar])

    # @user.avatar = params[:rating][:value]
    # if @user.save
    #   flash[:notice] = 'Avatar has been successfully updated'
    #   redirect_to user_path(@user.id)
    # else
    #   flash[:alert] = "Avatar failed to save"
    #   render :edit
    # end
  end





  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :role, :service, :avatar)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">Join The Community</div>
      <div class="panel-body">
        <h1>Change Profile Picture!</h1><br>
        <%= form_for edit_user_path(current_user.id), :html => { :multipart => true } do |form| %>
          <%= form.file_field :avatar %>
          <%= form.submit "upload" %>
        <% end %>
      </div>
    </div>
  </div>

app/views/users/index.html.erb
<h1>HomePage</h1><br>

<% if current_user && current_user.role == 'Provide Service'%>
  <h2>Users Requiring your service</h2>
  <% @users.each do |user| %>
    <% user.posts.each do |post| %>
      <% if post.post_type != current_user.role && post.service_type === current_user.service %>


    <div class="row">

        <div class="well">
            <div class="media">
              <a class="pull-left" href="#">
                <% if user.avatar.exists?%><%= image_tag(user.avatar.url(:thumb)) %><% else %><%=  image_tag("/app/assets/images/thumb/missing.png") %> <% end %>
            </a>

            </a>
            <div class="media-body">
              <h4 class="media-heading"><%= post.post_type %> || <%= post.service_type %></h4>
                <p class="text-right">By <%= link_to user.username + "- click to see complete posting ", user_path(user) %> </p>
                <p><%= post.content.split(" ").join(" ")[0..30] %>...</p>
                <ul class="list-inline list-unstyled">
              <li style="color:green"><span><i class="glyphicon glyphicon-calendar"></i> <%= post.created_at %></span></li>
                  <li>|</li>


            </ul>
             </div>
          </div>
        </div>
      </div>









      <% end %>
    <% end %>
  <% end %>









<% elsif current_user && current_user.role == 'Request Service'%>
  <h2>Users Providing your required service</h2>
  <% @users.each do |user| %>
    <% user.posts.each do |post| %>
      <% if post.post_type != current_user.role && post.service_type == current_user.service %>





      <div class="row">

          <div class="well">
              <div class="media">
                <a class="pull-left" href="#">
                  <% if user.avatar.exists?%><%= image_tag(user.avatar.url(:thumb)) %><% else %><%=  image_tag("/app/assets/images/thumb/missing.png") %> <% end %>
              </a>

              </a>
              <div class="media-body">
                <h4 class="media-heading"><%= post.post_type %> || <%= post.service_type %></h4>
                  <p class="text-right">By <%= link_to user.username + "- click to see complete posting ", user_path(user) %> </p>
                  <p><%= post.content.split(" ").join(" ")[0..30] %>...</p>
                  <ul class="list-inline list-unstyled">
                <li style="color:green"><span><i class="glyphicon glyphicon-calendar"></i> <%= post.created_at %></span></li>
                    <li>|</li>


              </ul>
               </div>
            </div>
          </div>
        </div>






      <% end %>
    <% end %>
  <% end %>
<% end %>















  <h2>All Posts</h2>
  <br>
  <% if current_user %>
    <% @users.each do |user| %>
      <% if user.posts.length > 0 %>
        <% user.posts.each do |post|%>





              <div class="well">
                <div class="media">
                  <a class="pull-left" href="#">
                    <% if user.avatar.exists?%><%= image_tag(user.avatar.url(:thumb)) %><% else %><%=  image_tag("/app/assets/images/thumb/missing.png") %> <% end %>
                </a>
                <div class="media-body">
                  <h4 class="media-heading"><%= post.post_type %> || <%= post.service_type%></h4>
                    <p class="text-right">By <%= link_to user.username + "- click to see complete posting ", user_path(user) %></p>
                    <div class="pull-right"></div>
                    <p><%= post.content.split(" ").join(" ")[0..30] %>...</p>
                    <ul class="list-inline list-unstyled">
                  <li style="color:green"><span><i class="glyphicon glyphicon-calendar"></i> <%= post.created_at %> </span></li>
                </ul>
                 </div>
              </div>
            </div>



      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">Join The Community</div>
      <div class="panel-body">
        <h1>Signup!</h1><br>

        <%= simple_form_for @user, validate: true do |f| %>
        <% if @user.errors.any? %>
          <div id="error_explanation">
            <div class="alert alert-danger">
              The form contains <%= pluralize(@user.errors.count, "error") %> errors
            </div>
            <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <div class="alert alert-warning">
                <li><%= msg %></li>
              </div>
            <% end %>
            </ul>
          </div>
        <% end %>


          <%= f.input :username, label: 'Username' %>
          <%= f.input :email, label: 'Email' %>
          <%= f.input :role, label: 'Role', collection: ['Provide Service', 'Request Service'] %>
          <%= f.input :service, label: 'Service', collection: ['Tutoring', 'Home Improvement', 'Personal Training'] %>
          <%= f.input :password, label: 'Password' %>
          <%= f.input :password_confirmation, label: 'Password Confirmation' %>
          <%= f.file_field :avatar, label: "Avatar" %><br>
          <%= f.button :submit %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-md-6">

  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <div class="jumbotron">
      <% if @user.avatar.exists? %>
        <%= image_tag(@user.avatar.url(:medium)) %>
      <% end %>
      <h1><%=@user.username%>'s Profile Page</h1>
    </div>
  </div>
</div>





<div class="row">

  <div class="col-xs-3">
    <div class="panel panel-default">
      <div class="panel-body">
        <% if @user.id != current_user.id%>
         <%= link_to 'Rate Me', new_user_rating_path(@user) %>
        <% end %>

        <h2>My Average Rating</h2>
        <% if @user.ratings.length > 0 %>
          <% my_ratings = [] %>
          <% @ratings.each do |rating| %>
            <% if rating.user_id == @user.id%>
              <% my_ratings.push(rating.value) %>
            <% end %>
          <% end %>
            <span class=" star-rating" data-score= <%= @user.average_rating(my_ratings) %>></span>
            (<%= @user.average_rating(my_ratings) %>)
        <% else %>
            <span class=" star-rating" data-score= <%= @user.average_rating([0]) %>></span>
            (<%= @user.average_rating([0]) %>)
        <% end %>

      </div>
    </div>
  </div>


  <div class="col-xs-6">
    <div class="panel panel-default">
      <div class="panel-body">
        <% if current_user.id == @user.id %>
          <%= link_to 'Make a Post', new_user_post_path(current_user.id) %>
        <% end %>
        <h2>My Posts</h2>
        <% @posts.each do |post| %>
        <div class="well">
          <div class="media">
            <div class="media-body">
          <h4 class="media-heading"><%= post.post_type %> || <%= post.service_type%></h4>

            <p class="text-right">By <%= link_to @user.username, user_path(@user) %></p>

            <p><%= post.content%>.</p>
            <ul class="list-inline list-unstyled">
          <li><span><i class="glyphicon glyphicon-calendar"></i> <%= post.created_at %> </span></li>
              <li>|</li>
              <li>
                 <span class="glyphicon glyphicon-star"></span>
                          <span class="glyphicon glyphicon-star"></span>
                          <span class="glyphicon glyphicon-star"></span>
                          <span class="glyphicon glyphicon-star"></span>
                          <span class="glyphicon glyphicon-star-empty"></span>
              </li>
              <li>|</li>
              <li>
              <!-- Use Font Awesome http://fortawesome.github.io/Font-Awesome/ -->
              <% if current_user && @user.id != current_user.id %>
                <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: 'post'%>
              <% else %>
                <%= link_to 'Edit', edit_user_post_path(@user, post)%>
                <%= link_to 'Delete', [@user, @post], method: :delete, data: {confirm: "Are you sure you want to delete this post? This cannot be undone!"} %>
            <% end %>
              </li>
        </ul>
         </div>
       </div>
     </div>



        <% end %>
      </div>
    </div>
  </div>

  <div class="col-xs-3">
    <div class="panel panel-default">
      <div class="panel-body">
        <h1>about</h1>

        <% if @user.id == current_user.id%>
          <h3>Update Profile pic </h3><br>
          <%= link_to 'Edit', edit_user_path(@user.id)%>
      <% end %>
      </div>
    </div>
  </div>

</div>






<br> <br>