config/routes.rb
Rails.application.routes.draw do

  root 'users#new'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  

  resources :users do
    resources :posts
    resources :ratings
  end

resources :conversations do
  resources :messages
 end


  get '/home' => 'users#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
 belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
 belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'

 has_many :messages, dependent: :destroy

 validates_uniqueness_of :sender_id, :scope => :recipient_id


 # make sure only 1 conversation can be had between users.
 scope :between, -> (sender_id,recipient_id) do
   where("(conversations.sender_id = ? AND conversations.recipient_id =?)
   OR (conversations.sender_id = ? AND conversations.recipient_id =?)",
   sender_id,recipient_id, recipient_id, sender_id)
 end



end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation

  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'



  validates_presence_of :body, :conversation_id, :sender_id, :recipient_id



  # method to show the created_at in a sexy way
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end

end

app/models/post.rb
class Post < ApplicationRecord

belongs_to :user

end

app/models/rating.rb
class Rating < ApplicationRecord

belongs_to :user

validates_presence_of :value
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password


  has_many :posts
  has_many :ratings
  has_many :conversations


  has_attached_file :avatar, styles: { :medium => "300x300>", :thumb => "100x100>" }, :default_url => ":assets/:medium/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  validates_presence_of :username, :email, :password_digest, :role, :service
  validates_uniqueness_of :username, :email


  def average_rating(array)
    sum = 0
    array.each do |rating|
      sum += rating
    end
    return (sum / array.length)
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action do
   @conversation = Conversation.find(params[:conversation_id])
  end


def index

  if @conversation.sender === current_user
    @user = @conversation.recipient
  else
    @user = @conversation.sender
  end




 @messages = @conversation.messages
  if @messages.length > 10
   @over_ten = true
   @messages = @messages[-10..-1]
  end
  if params[:m]
   @over_ten = false
   @messages = @conversation.messages
  end
 if @messages.last
  if @messages.last.sender_id != current_user.id
   @messages.last.read = true;
   @messages.last.save
  end
 end
 
 # @unread = @conversation.messages.where(read: false).where.not(id: nil).where.not(sender: current_user)
 @message = @conversation.messages.new
end



def new
 @message = @conversation.messages.new
end



def create
 @message = @conversation.messages.new(message_params)
 if @message.save
  redirect_to conversation_messages_path(@conversation)
 end
end



private
 def message_params
  params.require(:message).permit(:body, :sender_id, :recipient_id)
 end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def new
    @post = Post.new
    @user = User.find(params[:user_id])
  end


  def create
    @post = Post.new
    @user = User.find(params[:user_id])

    @post.post_type = params[:post][:post_type]
    @post.service_type = params[:post][:service_type]
    @post.content = params[:post][:content]
    @post.user_id = @user.id

    if @post.save
      flash[:notice] = 'Your Post has successfully been created'
      redirect_to home_path
    else
      flash[:alert] = "Post failed to save"
      render new_user_post_path(@user.id)
    end

  end

  def edit
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @user = User.find(params[:user_id])


    if @post.update(
      post_type: params[:post][:post_type],
      service_type: params[:post][:service_type],
      content: params[:post][:content])

        flash[:notice] = 'Your Comment has successfully updated'
        redirect_to home_path
      else
        flash[:alert] = "Comment failed to save"
        render new_user_post_path(@user.id)
      end
    end

    def destroy
      @user = User.find(params[:user_id])
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to home_path
    end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController

def index

end


def new
  @rating = Rating.new
  @user = User.find(params[:user_id])
end

def create
  @rating = Rating.new
  @user = User.find(params[:user_id])

  @rating.value = params[:rating][:value]
  @rating.user_id = @user.id

  if @rating.save
    flash[:notice] = 'Your Rating has successfully been created'
    redirect_to user_path(@user)
  else
    flash[:alert] = "Post failed to save"
    render new_user_rating_path(@user)
  end
end

def edit

end


def update

end

def destroy

end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create

    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/home'
    else
      redirect_to '/login'
    end

  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @users = User.all
    @posts = Post.all
  end



  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @conversations = Conversation.all
    @ratings = Rating.all
  end

  def new
    @user = User.new
    @rating = Rating.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.registration_confirmation(@user).deliver
      session[:user_id] = @user.id
      flash[:notice] = "Account successfully created"
      redirect_to users_path
    else
      render :new
    end
    @rating = Rating.new
  end



  def edit
    @user = User.find(params[:id])
  end



  def update
    @user = User.find(params[:id])
    @user.update_attribute(:avatar, params[:user][:avatar])

    # @user.avatar = params[:rating][:value]
    # if @user.save
    #   flash[:notice] = 'Avatar has been successfully updated'
    #   redirect_to user_path(@user.id)
    # else
    #   flash[:alert] = "Avatar failed to save"
    #   render :edit
    # end
  end





  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :role, :service, :avatar)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobFair</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "http://code.jquery.com/jquery-2.1.1.min.js" %>

  </head>

  <body>

    <div class="container">
      <% if current_user%>
      <header class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" name="button" class="navbar-toggle collapsed" d>

            </button>


          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li><%= link_to('Homepage', home_path) %></li>
              <li><%= link_to('My Profile', user_path(current_user.id))%></li>
              <li><%= link_to 'Inbox', conversations_path %></li>
              <li><%= link_to 'Logout', logout_path %> </li>
            </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><h5>signed in as <%= current_user.username %> </h5></li>
            <% if current_user.avatar.exists? %>
              <li><%= image_tag(current_user.avatar.url(:thumb)) %></li>
            <% end %>
         </ul>
        </div>
      </div>
    </header>




    <% else %>
    <header class="navbar  navbar-default">
      <div class="navbar-class">
        <div class="container">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Login', login_path %></li>
            <li><%= link_to 'Signup', new_user_path %></li>
          </ul>
        </div>
      </div>
  </header>
  <% end %>

  <script>

    $('.star-rating').raty({
      path: '/assets',
      readOnly: true,
      score: function () {
        return $(this).attr('data-score');
      }
    });
  </script>


  <%= yield %>



  <div class="row">
  <hr>
    <div class="col-lg-12">
      <div class="col-md-8">
        <a href="#">Terms of Service</a> | <a href="#">Privacy</a>
      </div>
      <div class="col-md-4">
        <p class="muted pull-right">© 2017 JobFair. All rights reserved</p>
      </div>
    </div>
  </div>
</div>


  </body>
</html>